# Generated by Django 4.0.6 on 2022-08-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_foodcategory_food'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='food',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
