# Generated by Django 4.0.6 on 2022-10-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
