# Generated by Django 4.0.6 on 2022-08-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_food_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='date',
        ),
    ]
