# Generated by Django 4.0.6 on 2022-10-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_foodcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='price_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
