# Generated by Django 4.0.6 on 2022-10-20 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_combo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comboitem',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.food'),
        ),
    ]
