# Generated by Django 4.0.6 on 2022-10-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_ordered_date_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
