# Generated by Django 4.0.6 on 2022-10-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_order_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price_before',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
