# Generated by Django 4.0.6 on 2022-10-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_offer_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
