# Generated by Django 4.0.6 on 2022-10-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_orderitem_food'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='completed',
            new_name='cancelled',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('T', 'Order Taken'), ('P', 'Processing'), ('S', 'Shipped'), ('D', 'Delivered')], default='T', max_length=2),
        ),
    ]
