# Generated by Django 4.0.6 on 2022-11-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_foodcategory_starts_at_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='starts_at',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
