# Generated by Django 4.0.6 on 2022-11-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_businessinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='fb',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='insta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
