# Generated by Django 4.0.6 on 2022-11-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
